from moduller.tarayici import Tarayici
from selenium.webdriver.common.by import By
tarayici_nesnesi = Tarayici()
tarayici = tarayici_nesnesi.al()
from time import sleep

tarayici.get("https://twitter.com/i/flow/login?input_flow_data=%7B%22requested_variant%22%3A%22eyJsYW5nIjoidHIifQ%3D%3D%22%7D")
sleep(2)
x = tarayici.find_element(By.XPATH, '//*[@id="layers"]/div/div/div/div/div/div/div[2]/div[2]/div/div/div[2]/div[2]/div/div/div/div[5]/label/div/div[2]/div/input')
x.send_keys("denemebotutaihl@gmail.com")
giris = tarayici.find_element(By.XPATH, "(//div[@class='css-18t94o4 css-1dbjc4n r-sdzlij r-1phboty r-rs99b7 r-ywje51 r-usiww2 r-2yi16 r-1qi8awa r-1ny4l3l r-ymttw5 r-o7ynqc r-6416eg r-lrvibr r-13qz1uu'])[1]")
giris.click()
sleep(1)
y = tarayici.find_element(By.XPATH, '//*[@id="layers"]/div/div/div/div/div/div/div[2]/div[2]/div/div/div[2]/div[2]/div[1]/div/div[2]/label/div/div[2]/div/input')
y.send_keys("@denemebotu1")
devam = tarayici.find_element(By.XPATH, '//*[@id="layers"]/div/div/div/div/div/div/div[2]/div[2]/div/div/div[2]/div[2]/div[2]/div/div/div/div')
devam.click()
sleep(1)
z = tarayici.find_element(By.XPATH, '//*[@id="layers"]/div/div/div/div/div/div/div[2]/div[2]/div/div/div[2]/div[2]/div[1]/div/div/div[3]/div/label/div/div[2]/div[1]/input')
z.send_keys("bottaihl123")
devam2 = tarayici.find_element(By.XPATH, '//*[@id="layers"]/div/div/div/div/div/div/div[2]/div[2]/div/div/div[2]/div[2]/div[2]/div/div[1]/div/div/div')
devam2.click()
sleep(5)
tweet = tarayici.find_element(By.XPATH, "(//div[@class='public-DraftStyleDefault-block public-DraftStyleDefault-ltr'])[1]")
tweet.send_keys("@star_dimension")
sleep(2)
kisi = tarayici.find_element(By.XPATH, "(//div[@class='css-1dbjc4n r-1awozwy r-18u37iz r-1wtj0ep'])[1]")
kisi.click()
sleep(1)
yayin = tarayici.find_element(By.XPATH, "(//div[@class='css-18t94o4 css-1dbjc4n r-l5o3uw r-42olwf r-sdzlij r-1phboty r-rs99b7 r-19u6a5r r-2yi16 r-1qi8awa r-1ny4l3l r-ymttw5 r-o7ynqc r-6416eg r-lrvibr'])[1]")
yayin.click()
sleep(2)
ss = tarayici.find_element(By.XPATH, "(//body)[1]")
ss.screenshot("./foto/twiter.png")

